package httpx

import (
	"bytes"
	"embed"
	"fmt"
	"html/template"
	"io/fs"
	"net/http"
	"strings"
	"time"

	"github.com/milhamsuryapratama/diff-checker/internal/docmodel"
)

//go:embed templates/*.gohtml
var templateFS embed.FS

//go:embed static
var staticFS embed.FS

// tpl is parsed once at startup. A parse error here is a programming error, so
// it panics rather than degrading to a broken page at request time.
var tpl = template.Must(
	template.New("").Funcs(funcs).ParseFS(templateFS, "templates/*.gohtml"))

var funcs = template.FuncMap{
	"severityClass": severityClass,
	"classBadge":    classBadge,
	"pct":           func(f float64) string { return fmt.Sprintf("%.0f%%", f*100) },
	"usd":           func(f float64) string { return fmt.Sprintf("$%.4f", f) },
	"dur": func(d time.Duration) string {
		if d < time.Second {
			return fmt.Sprintf("%dms", d.Milliseconds())
		}
		return fmt.Sprintf("%.1fs", d.Seconds())
	},
	"sideLabel": func(s docmodel.Side) string {
		if s.Resolved() == docmodel.SidePrev {
			return "versi lama"
		}
		return "versi baru"
	},
	// highlight renders the word-level diff markup produced by textdiff.
	//
	// The <b> tags are generated by our own diff code, never by a model and
	// never taken from the document, and the document text inside them was
	// HTML-escaped when the markup was built. Marking it safe here is therefore
	// sound — but it is the single place in the UI where that is true, which is
	// why it is a named helper rather than an inline template.HTML conversion.
	"highlight": func(s string) template.HTML { return template.HTML(s) },
	"hasPrefix": strings.HasPrefix,
	"add":       func(a, b int) int { return a + b },
	// dict builds an inline map so a shared block can be given named
	// arguments, e.g. {{template "head" (dict "Title" "Laporan")}}.
	"dict": func(kv ...any) (map[string]any, error) {
		if len(kv)%2 != 0 {
			return nil, fmt.Errorf("dict butuh jumlah argumen genap, dapat %d", len(kv))
		}
		m := make(map[string]any, len(kv)/2)
		for i := 0; i < len(kv); i += 2 {
			k, ok := kv[i].(string)
			if !ok {
				return nil, fmt.Errorf("kunci dict harus string, dapat %T", kv[i])
			}
			m[k] = kv[i+1]
		}
		return m, nil
	},
}

func severityClass(s docmodel.Severity) string {
	switch s {
	case docmodel.SeverityCritical:
		return "sev-critical"
	case docmodel.SeverityMajor:
		return "sev-major"
	case docmodel.SeverityMinor:
		return "sev-minor"
	}
	return "sev-info"
}

// classBadge distinguishes proven findings from model suggestions.
//
// This is the load-bearing piece of UI in the whole product: a legal reviewer
// who cannot tell which findings are reproducible will discount all of them.
func classBadge(c docmodel.Class) string {
	if c == docmodel.ClassAdvisory {
		return "badge-advisory"
	}
	return "badge-verified"
}

// render executes a template into a buffer first, so a template error produces
// a clean 500 rather than a half-written page with a 200 already sent.
func (s *Server) render(w http.ResponseWriter, name string, data any) {
	var buf bytes.Buffer
	if err := tpl.ExecuteTemplate(&buf, name, data); err != nil {
		s.log.Error("gagal merender template", "template", name, "err", err)
		http.Error(w, "gagal merender halaman", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = buf.WriteTo(w)
}

func staticHandler() http.Handler {
	sub, err := fs.Sub(staticFS, "static")
	if err != nil {
		panic(err)
	}
	return http.FileServer(http.FS(sub))
}
